"""Configuration values shared across tasks."""

LEARNING_RATE = 6e-5
WEIGHT_DECAY = 0.01
WARMUP_EPOCHS = 5
MODEL_PATH = "model.pt"
BATCH_SIZE = 1
VAL_BATCH_SIZE = 1
NUM_WORKERS = 1
PREFETCH_FACTOR = 1
VAL_INTERVAL = 1
GRAD_ACCUM_STEPS = 8
USE_GRADIENT_CHECKPOINTING = False
USE_TORCH_COMPILE = True